# Generated by Django 3.0.6 on 2020-05-28 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pvp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='nick_fplayer',
            field=models.CharField(default='Anonim', max_length=20),
        ),
        migrations.AddField(
            model_name='game',
            name='nick_splayer',
            field=models.CharField(default='Anonim', max_length=20),
        ),
        migrations.AddField(
            model_name='game',
            name='scores_fplayer',
            field=models.CharField(default='10', max_length=2),
        ),
        migrations.AddField(
            model_name='game',
            name='scores_splayer',
            field=models.CharField(default='10', max_length=2),
        ),
        migrations.AddField(
            model_name='game',
            name='status',
            field=models.CharField(choices=[('free', 'FREE'), ('ingame', 'INGAME')], default='free', max_length=20),
        ),
        migrations.AddField(
            model_name='task',
            name='answer',
            field=models.CharField(default='0', max_length=25),
        ),
        migrations.AddField(
            model_name='task',
            name='task',
            field=models.CharField(default='0', max_length=25),
        ),
    ]
