# Generated by Django 3.0.6 on 2020-05-28 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pvp', '0002_auto_20200528_2117'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='nick_fplayer',
            new_name='nick_green_player',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='nick_splayer',
            new_name='nick_red_player',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='scores_fplayer',
            new_name='scores_green_player',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='scores_splayer',
            new_name='scores_red_player',
        ),
    ]
