# Generated by Django 3.0.6 on 2020-05-28 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pvp', '0003_auto_20200528_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='nick_green_player',
            field=models.CharField(default='Anonim', max_length=15),
        ),
        migrations.AlterField(
            model_name='game',
            name='nick_red_player',
            field=models.CharField(default='Anonim', max_length=15),
        ),
    ]
